# Dev values for delivery.
nameOverride: delivery
exports:
  data:
    replicaCount: 5
    image:
      pullPolicy: Always
    telemetry:
      level: "Information"
    reason: "new dev deploy"
    current: true
    ingress:
      class: "nginx-dev"
    resources:
      requests:
        cpu: 300m
        memory: 450Mi
      limits:
        cpu: 530m
        memory: 800Mi
