# Dev values for website.
nameOverride: website
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: Always
    telemetry:
      level: "Information"
    reason: "new dev deploy"
    current: true
    ingress:
      class: "nginx-dev"
    resources:
      requests:
        cpu: 442m
        memory: 100Mi
      limits:
        cpu: 664m
        memory: 140Mi
