# Production values for website.
nameOverride: website
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
    telemetry:
      level: "Error"
    reason: "new prod deploy"
    ingress:
      class: "nginx-prod"
    resources:
      requests:
        cpu: 100m
        memory: 350Mi
      limits:
        cpu: 200m
        memory: 500Mi
